/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.aes;
import javax.swing.JFileChooser;
import java.io.File;
/**
 *
 * @author H.E.S
 */
public class interfacee extends javax.swing.JFrame {
    private String lastLatex = "";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfacee.class.getName());

    /**
     * Creates new form interfacee
     */
    public interfacee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Encrypt");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("AES Encryption Tool");

        jLabel2.setText("Text to process");

        jLabel3.setText("Result");

        jButton3.setText("Choose a file");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel4.setText("selected file:");

        jButton4.setText("Export pdf");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private File selectedFile = null;  // pour stocker le fichier choisi
private String textToProcess = "";  // texte à traiter
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // TODO add your handling code here:
                                        
              
                                           
    // Créer un JFileChooser
    JFileChooser fileChooser = new JFileChooser();
    
    // Ajouter un filtre pour n'accepter que les fichiers .txt
    javax.swing.filechooser.FileNameExtensionFilter filter =
            new javax.swing.filechooser.FileNameExtensionFilter("Text Files", "txt");
    fileChooser.setFileFilter(filter);

    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        selectedFile = fileChooser.getSelectedFile();
        jLabel4.setText("Selected file: " + selectedFile.getName());

        // Lire le contenu du fichier et l'afficher dans jTextArea1
        try (java.util.Scanner sc = new java.util.Scanner(selectedFile)) {
            StringBuilder sb = new StringBuilder();
            while (sc.hasNextLine()) {
                sb.append(sc.nextLine()).append("\n");
            }
            jTextArea1.setText(sb.toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


  textToProcess = jTextArea1.getText();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

 /* String text = jTextArea1.getText();
        String KEY = KeyGeneratorUtil.generateKey(16);
        AESHandler handler = new AESHandler(text, KEY);
        handler.AESEncrypting();

        String solution = handler.getLatexSolution();
        System.out.println(solution); 
        LatexHandler latexHandler = new LatexHandler(solution);
        latexHandler.generatePDF();
jTextArea1.setText("");*/
 
                                            
    String text = jTextArea1.getText();

    if (text.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Enter text first!");
        return;
    }

    String KEY = KeyGeneratorUtil.generateKey(16);
    AESHandler handler = new AESHandler(text, KEY);
    handler.AESEncrypting();

    // stocker le résultat latex
    lastLatex = handler.getLatexSolution();

    javax.swing.JOptionPane.showMessageDialog(this, "Encryption done!");
 

                                         
    
        
   

   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                                                 
                                           
                                          
                                           

                                             
                                        
                         
    if (lastLatex.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Click Encrypt first!");
        return;
    }

    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Save PDF");

    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();

        String path = fileToSave.getAbsolutePath();
        if (!path.endsWith(".pdf")) {
            path += ".pdf";
        }

        try {
            // créer fichier temporaire
            File texFile = new File("temp.tex");
            java.io.FileWriter writer = new java.io.FileWriter(texFile);
            writer.write(lastLatex);
            writer.close();

            // compiler latex
            ProcessBuilder pb = new ProcessBuilder(
                "C:\\Program Files\\MiKTeX\\miktex\\bin\\x64\\pdflatex.exe",
                "temp.tex"
            );

            pb.directory(new File(System.getProperty("user.dir")));
            Process process = pb.start();
            process.waitFor();

            // déplacer PDF
            File generatedPDF = new File("temp.pdf");
            java.nio.file.Files.move(
                    generatedPDF.toPath(),
                    new File(path).toPath(),
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING
            );

            javax.swing.JOptionPane.showMessageDialog(this, "PDF saved!");
            
            // vider le textarea
            jTextArea1.setText("");
            
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error generating PDF!");
        }
    }
                  
                                            
   

    

   

   

   

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfacee().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
